/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hc_jnidemo11036_NdkTools */

#ifndef _Included_com_hc_jnidemo11036_NdkTools
#define _Included_com_hc_jnidemo11036_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hc_jnidemo11036_NdkTools
 * Method:    getStrFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hc_jnidemo11036_NdkTools_getStrFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
